spring:
  application:
    name: springboot-pulsar
  pulsar:
    client:
      service-url: pulsar://localhost:6650
      #service-url: pulsar+ssl://127.0.0.1:6651 # 开启 SSL 安全通信的连接配置方式
      #auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken # 示例使用 JWT Token 认证插件
      #authentication:
      #  token: YOUR_PULSAR_TOKEN # token 信息

    defaults:
      type-mappings:
        - message-type: com.example.pulsar.model.Message
          schema-info:
            schema-type: JSON

    listener:
      concurrency: 2